# Generated by Django 5.0.14 on 2026-08-19 11:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deduplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idempotencyrecord',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
