# Generated by Django 5.0.14 on 2026-08-30 12:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0014_alter_lessondraft_managers_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Deck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "deck_type",
                    models.CharField(
                        choices=[
                            ("custom", "Custom"),
                            ("lesson", "Lesson-Based"),
                            ("skill", "Skill-Based"),
                            ("imported", "Imported"),
                        ],
                        db_index=True,
                        default="custom",
                        max_length=20,
                    ),
                ),
                (
                    "source_skill_slug",
                    models.SlugField(
                        blank=True,
                        help_text="Skill tag slug this deck is associated with.",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6366f1",
                        help_text="Hex color for UI display.",
                        max_length=7,
                    ),
                ),
                ("icon_emoji", models.CharField(default="🃏", max_length=10)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Allow other users to clone this deck."
                    ),
                ),
                ("clone_count", models.PositiveIntegerField(default=0)),
                ("card_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flashcard_decks",
                        to="content.lesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flashcard_decks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DeckShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cloned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cloned_decks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cloned_deck",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_share",
                        to="flashcards.deck",
                    ),
                ),
                (
                    "source_deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="flashcards.deck",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Flashcard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "front",
                    models.TextField(
                        help_text="Question or prompt on the front of the card."
                    ),
                ),
                (
                    "back",
                    models.TextField(help_text="Answer or explanation on the back."),
                ),
                (
                    "hint",
                    models.TextField(
                        blank=True, help_text="Optional hint shown before flipping."
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Free-form tags for filtering.",
                    ),
                ),
                (
                    "media_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional image/audio URL attached to the card.",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "is_suspended",
                    models.BooleanField(
                        default=False,
                        help_text="Suspended cards are excluded from review sessions.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="flashcards.deck",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ReviewSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "easiness_factor",
                    models.FloatField(
                        default=2.5,
                        help_text="SM-2 easiness factor (EF ≥ 1.3).",
                        validators=[
                            django.core.validators.MinValueValidator(1.3),
                            django.core.validators.MaxValueValidator(3.0),
                        ],
                    ),
                ),
                (
                    "interval_days",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Current interval in days before next review.",
                    ),
                ),
                (
                    "repetition",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Consecutive correct reviews (lapses reset to 0).",
                    ),
                ),
                (
                    "next_review",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this card is next due for review.",
                    ),
                ),
                ("last_reviewed", models.DateTimeField(blank=True, null=True)),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                ("correct_reviews", models.PositiveIntegerField(default=0)),
                (
                    "streak",
                    models.PositiveIntegerField(
                        default=0, help_text="Consecutive 'good' or better ratings."
                    ),
                ),
                (
                    "is_new",
                    models.BooleanField(
                        default=True,
                        help_text="True until the card has been reviewed at least once.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "flashcard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_schedules",
                        to="flashcards.flashcard",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["next_review"],
            },
        ),
        migrations.CreateModel(
            name="ReviewLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (0, "Again (Blackout)"),
                            (1, "Hard"),
                            (2, "Good"),
                            (3, "Easy"),
                            (4, "Perfect"),
                        ]
                    ),
                ),
                ("prev_easiness", models.FloatField()),
                ("prev_interval", models.PositiveIntegerField()),
                ("prev_repetition", models.PositiveIntegerField()),
                ("new_easiness", models.FloatField()),
                ("new_interval", models.PositiveIntegerField()),
                ("new_repetition", models.PositiveIntegerField()),
                (
                    "response_time_ms",
                    models.PositiveIntegerField(
                        default=0, help_text="Milliseconds the user took to answer."
                    ),
                ),
                ("reviewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "flashcard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_logs",
                        to="flashcards.flashcard",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="flashcards.reviewschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["-reviewed_at"],
            },
        ),
        migrations.CreateModel(
            name="StudySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("due", "Due Reviews"),
                            ("learn", "New Cards"),
                            ("review", "Review Session"),
                            ("cram", "Cram Mode"),
                        ],
                        default="due",
                        max_length=10,
                    ),
                ),
                ("cards_reviewed", models.PositiveIntegerField(default=0)),
                ("cards_correct", models.PositiveIntegerField(default=0)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("xp_earned", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deck",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_sessions",
                        to="flashcards.deck",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="deck",
            index=models.Index(
                fields=["user", "-updated_at"], name="idx_deck_user_time"
            ),
        ),
        migrations.AddIndex(
            model_name="deck",
            index=models.Index(
                fields=["is_public", "clone_count"], name="idx_deck_public_clone"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="deckshare",
            unique_together={("source_deck", "cloned_by")},
        ),
        migrations.AddIndex(
            model_name="flashcard",
            index=models.Index(
                fields=["deck", "is_suspended"], name="idx_fc_deck_suspended"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewschedule",
            index=models.Index(fields=["user", "next_review"], name="idx_rs_user_next"),
        ),
        migrations.AddIndex(
            model_name="reviewschedule",
            index=models.Index(fields=["user", "is_new"], name="idx_rs_user_new"),
        ),
        migrations.AlterUniqueTogether(
            name="reviewschedule",
            unique_together={("user", "flashcard")},
        ),
        migrations.AddIndex(
            model_name="reviewlog",
            index=models.Index(
                fields=["user", "-reviewed_at"], name="idx_rl_user_time"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewlog",
            index=models.Index(
                fields=["flashcard", "rating"], name="idx_rl_card_rating"
            ),
        ),
        migrations.AddIndex(
            model_name="studysession",
            index=models.Index(fields=["user", "-started_at"], name="idx_ss_user_time"),
        ),
    ]
