# Generated by Django 5.0.14 on 2026-08-22 16:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("burnout_detection", "0001_burnoutactivityday"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BurnoutMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                ("total_contributors", models.IntegerField(default=0)),
                ("at_risk_contributors", models.IntegerField(default=0)),
                ("critical_contributors", models.IntegerField(default=0)),
                ("low_risk_count", models.IntegerField(default=0)),
                ("medium_risk_count", models.IntegerField(default=0)),
                ("high_risk_count", models.IntegerField(default=0)),
                ("critical_risk_count", models.IntegerField(default=0)),
                ("average_burnout_score", models.FloatField(default=0.0)),
                ("average_sentiment", models.FloatField(default=0.0)),
                ("burnout_trend", models.FloatField(default=0.0)),
                ("sentiment_trend", models.FloatField(default=0.0)),
                ("total_interventions", models.IntegerField(default=0)),
                ("successful_interventions", models.IntegerField(default=0)),
                ("intervention_success_rate", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="BurnoutSignal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "signal_type",
                    models.CharField(
                        choices=[
                            ("declining_activity", "Declining Activity"),
                            ("negative_sentiment", "Negative Sentiment"),
                            ("increased_response_time", "Increased Response Time"),
                            ("reduced_reviews", "Reduced Reviews"),
                            ("irregular_pattern", "Irregular Pattern"),
                        ],
                        max_length=30,
                    ),
                ),
                ("severity", models.CharField(max_length=20)),
                ("description", models.TextField()),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="burnout_signals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="Intervention",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "intervention_type",
                    models.CharField(
                        choices=[
                            ("encouragement", "Encouragement"),
                            ("workload_reduction", "Workload Reduction"),
                            ("break_suggestion", "Break Suggestion"),
                            ("support_offer", "Support Offer"),
                            ("resource_sharing", "Resource Sharing"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("acknowledged", "Acknowledged"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "signal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interventions",
                        to="burnout_detection.burnoutsignal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interventions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContributorActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("commits_last_week", models.IntegerField(default=0)),
                ("commits_last_month", models.IntegerField(default=0)),
                ("reviews_last_week", models.IntegerField(default=0)),
                ("reviews_last_month", models.IntegerField(default=0)),
                ("comments_last_week", models.IntegerField(default=0)),
                ("comments_last_month", models.IntegerField(default=0)),
                ("avg_response_time", models.FloatField(default=0.0)),
                ("avg_review_response_time", models.FloatField(default=0.0)),
                ("activity_trend", models.FloatField(default=0.0)),
                ("review_trend", models.FloatField(default=0.0)),
                ("response_trend", models.FloatField(default=0.0)),
                ("sentiment_score", models.FloatField(default=0.0)),
                ("sentiment_trend", models.FloatField(default=0.0)),
                ("burnout_score", models.FloatField(default=0.0)),
                ("burnout_risk", models.CharField(default="low", max_length=20)),
                ("detected_at", models.DateTimeField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-burnout_score"],
                "indexes": [
                    models.Index(
                        fields=["user", "burnout_score"],
                        name="burnout_det_user_id_0e61da_idx",
                    ),
                    models.Index(
                        fields=["burnout_risk"], name="burnout_det_burnout_358c04_idx"
                    ),
                ],
            },
        ),
    ]
