# Generated by Django 5.0.14 on 2026-08-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("errors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="errorevent",
            name="exception_class",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="errorgroup",
            name="exception_class",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
    ]
