# Generated by Django 5.0.14 on 2026-08-30 08:05

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_delete_streakfreeze"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="issue",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="issue",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
