# Generated by Django 5.1.15 on 2026-07-07 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class SafeAddConstraint(migrations.AddConstraint):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        try:
            super().database_forwards(app_label, schema_editor, from_state, to_state)
        except Exception as e:
            if "already exists" in str(e).lower():
                pass
            else:
                raise


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0017_merge_20260630_1426"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userbadge",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="lessonprogress",
            name="attempt_count",
            field=models.IntegerField(default=0),
        ),
        SafeAddConstraint(
            model_name="userbadge",
            constraint=models.UniqueConstraint(
                fields=("user", "badge"), name="unique_user_badge_award"
            ),
        ),
    ]
