# Generated by Django 5.1.15 on 2026-07-03 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class SafeCreateModel(migrations.CreateModel):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.name)
        table_name = model._meta.db_table
        with schema_editor.connection.cursor() as cursor:
            existing_tables = schema_editor.connection.introspection.table_names(cursor)
        if table_name in existing_tables:
            return
        try:
            super().database_forwards(app_label, schema_editor, from_state, to_state)
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0018_plagiarismreport_alter_userbadge_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        SafeCreateModel(
            name="StreakProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_streak", models.PositiveIntegerField(default=0)),
                ("longest_streak", models.PositiveIntegerField(default=0)),
                ("last_activity_date", models.DateField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streak_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "current_streak"],
                        name="idx_streak_user_current",
                    )
                ],
            },
        ),
    ]
