# Generated by Django 5.1.15 on 2026-07-03 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class SafeCreateModel(migrations.CreateModel):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.name)
        table_name = model._meta.db_table
        with schema_editor.connection.cursor() as cursor:
            existing_tables = schema_editor.connection.introspection.table_names(cursor)
        if table_name in existing_tables:
            return
        try:
            super().database_forwards(app_label, schema_editor, from_state, to_state)
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_lessonthread_lessoncomment_and_more"),
        ("progress", "0020_merge_20260703_0835"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        SafeCreateModel(
            name="LessonBookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="content.lesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "lesson")},
            },
        ),
    ]
