# Generated by Django 4.2.30 on 2026-07-06 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class SafeAlterUniqueTogether(migrations.AlterUniqueTogether):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == "postgresql":
            model_name = getattr(self, "name", getattr(self, "model_name", None))
            model = from_state.apps.get_model(app_label, model_name)
            table_name = model._meta.db_table
            with schema_editor.connection.cursor() as cursor:
                constraints = schema_editor.connection.introspection.get_constraints(
                    cursor, table_name
                )
            has_unique = any(
                c_info.get("unique") and set(c_info.get("columns", [])) == {"user_id", "badge_id"}
                for c_info in constraints.values()
            )
            if not has_unique:
                return
        try:
            super().database_forwards(app_label, schema_editor, from_state, to_state)
        except Exception:
            pass


class SafeAddConstraint(migrations.AddConstraint):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = from_state.apps.get_model(app_label, self.model_name)
        table_name = model._meta.db_table
        with schema_editor.connection.cursor() as cursor:
            existing_constraints = schema_editor.connection.introspection.get_constraints(
                cursor, table_name
            )
        if self.constraint.name in existing_constraints:
            return
        try:
            super().database_forwards(app_label, schema_editor, from_state, to_state)
        except Exception:
            pass


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("progress", "0023_lessonprogresssync"),
    ]

    operations = [
        migrations.CreateModel(
            name="XPEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("lesson", "Lesson"),
                            ("exercise", "Exercise"),
                            ("pr", "Pull Request"),
                            ("issue", "Issue"),
                            ("review", "Review"),
                            ("badge", "Badge"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_id", models.PositiveIntegerField(blank=True, null=True)),
                ("base_points", models.PositiveIntegerField()),
                ("multiplier", models.FloatField(default=1.0)),
                ("xp_delta", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        SafeAlterUniqueTogether(
            name="userbadge",
            unique_together=set(),
        ),
        SafeAddConstraint(
            model_name="userbadge",
            constraint=models.UniqueConstraint(
                fields=("user", "badge"), name="unique_user_badge_award"
            ),
        ),
        migrations.AddField(
            model_name="xpevent",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="xp_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="xpevent",
            index=models.Index(
                fields=["user", "source_type"], name="idx_xp_user_source"
            ),
        ),
        migrations.AddIndex(
            model_name="xpevent",
            index=models.Index(fields=["-created_at"], name="idx_xp_created_desc"),
        ),
    ]
