# Generated by Django 5.0.14 on 2026-08-13 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0037_weekly_digest_log'),
    ]

    operations = [
    ]
