# Generated by Django 5.0.14 on 2026-08-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0038_merge_0008b_and_0037'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lessonprogress',
            name='progress_lessonprogress_attempt_count_gte_0',
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='attempt_count',
            field=models.IntegerField(default=0),
        ),
    ]
