# Generated by Django 5.0.14 on 2026-07-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_adminauditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("view_name", models.CharField(db_index=True, max_length=255)),
                ("method", models.CharField(max_length=10)),
                ("duration_ms", models.FloatField()),
                ("db_query_count", models.IntegerField()),
                ("db_duration_ms", models.FloatField()),
                ("cache_hits", models.IntegerField(default=0)),
                ("cache_misses", models.IntegerField(default=0)),
                ("serialization_ms", models.FloatField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user_id",
                    models.IntegerField(
                        blank=True, help_text="Anonymized after 24h", null=True
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["view_name", "timestamp"],
                        name="core_perfor_view_na_d7b1aa_idx",
                    )
                ],
            },
        ),
    ]
