# Generated by Django 5.0.14 on 2026-07-31 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_moduledraft_lessondraft_quizdraft'),
        ('rbac', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lessons', models.ManyToManyField(blank=True, related_name='learning_paths', to='content.lesson')),
                ('required_roles', models.ManyToManyField(blank=True, help_text='Roles required to access this learning path. If empty, public to all authenticated users.', related_name='learning_paths', to='rbac.role')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
