# Generated by Django 5.0.14 on 2026-08-30 12:10

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0013_lessondraft_deleted_at_lessondraft_deleted_by_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="lessondraft",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="moduledraft",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
