# Generated by Django 5.0.14 on 2026-07-27 15:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AutoFixPR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pr_number", models.IntegerField()),
                ("pr_url", models.URLField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("MERGED", "Merged"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("packages_updated", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("package_name", models.CharField(max_length=128)),
                ("ecosystem", models.CharField(default="python", max_length=32)),
                ("current_version", models.CharField(default="0.0.0", max_length=64)),
                ("latest_version", models.CharField(default="0.0.0", max_length=64)),
                ("days_vulnerable", models.IntegerField(default=0)),
                ("decay_rate", models.FloatField(default=0.0)),
                ("security_score", models.IntegerField(default=100)),
                ("last_checked_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-days_vulnerable", "package_name"],
            },
        ),
        migrations.CreateModel(
            name="VulnerabilityItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cve_id", models.CharField(max_length=64)),
                ("package_name", models.CharField(max_length=128)),
                ("installed_version", models.CharField(max_length=64)),
                (
                    "fixed_version",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        max_length=16,
                    ),
                ),
                ("ecosystem", models.CharField(default="python", max_length=32)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("FIX_PENDING", "Fix Pending"),
                            ("RESOLVED", "Resolved"),
                            ("SUPPRESSED", "Suppressed"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("suppressed_until", models.DateField(blank=True, null=True)),
                ("suppression_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-severity", "cve_id"],
            },
        ),
        migrations.CreateModel(
            name="VulnerabilityReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("commit_sha", models.CharField(blank=True, default="", max_length=64)),
                (
                    "branch",
                    models.CharField(blank=True, default="main", max_length=128),
                ),
                ("ecosystem", models.CharField(default="ALL", max_length=64)),
                ("total_vulnerabilities", models.IntegerField(default=0)),
                ("critical_count", models.IntegerField(default=0)),
                ("high_count", models.IntegerField(default=0)),
                ("medium_count", models.IntegerField(default=0)),
                ("low_count", models.IntegerField(default=0)),
                ("summary_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-scan_date"],
            },
        ),
        migrations.CreateModel(
            name="VulnerabilitySuppression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cve_id", models.CharField(max_length=64)),
                (
                    "package_name",
                    models.CharField(blank=True, default="*", max_length=128),
                ),
                ("reason", models.TextField()),
                ("expires_at", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="projectdependency",
            constraint=models.UniqueConstraint(
                fields=("package_name", "ecosystem"), name="unique_package_ecosystem"
            ),
        ),
        migrations.AddField(
            model_name="vulnerabilityitem",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="security.vulnerabilityreport",
            ),
        ),
    ]
