# Generated by Django 5.0.14 on 2026-08-19 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RBAC',
            fields=[
            ],
            options={
                'verbose_name': 'RBAC Audit Event',
                'verbose_name_plural': 'RBAC Audit Events',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('audit.auditevent',),
        ),
    ]
