# Generated by Django 5.0.14 on 2026-08-13 11:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ml_triage", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("category", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContributorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vcs_provider", models.CharField(default="github", max_length=50)),
                ("vcs_username", models.CharField(max_length=255)),
                ("vcs_data", models.JSONField(default=dict)),
                ("primary_languages", models.JSONField(default=list)),
                ("all_languages", models.JSONField(default=list)),
                ("frameworks", models.JSONField(default=list)),
                ("skill_levels", models.JSONField(default=dict)),
                ("total_commits", models.IntegerField(default=0)),
                ("total_repos", models.IntegerField(default=0)),
                ("contributions_count", models.IntegerField(default=0)),
                ("years_experience", models.FloatField(default=0.0)),
                ("interests", models.JSONField(default=list)),
                ("preferred_areas", models.JSONField(default=list)),
                ("total_recommendations", models.IntegerField(default=0)),
                ("accepted_recommendations", models.IntegerField(default=0)),
                ("success_rate", models.FloatField(default=0.0)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-success_rate"],
            },
        ),
        migrations.CreateModel(
            name="NewcomerFriendlinessScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description_quality", models.FloatField(default=0.0)),
                ("scope_clarity", models.FloatField(default=0.0)),
                ("support_availability", models.FloatField(default=0.0)),
                ("skill_match", models.FloatField(default=0.0)),
                ("overall_score", models.FloatField(default=0.0)),
                ("has_good_first_issue_label", models.BooleanField(default=False)),
                ("has_mentor", models.BooleanField(default=False)),
                ("has_documentation", models.BooleanField(default=False)),
                ("estimated_time_hours", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "issue",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friendliness_score",
                        to="ml_triage.issue",
                    ),
                ),
            ],
            options={
                "ordering": ["-overall_score"],
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("match_score", models.FloatField(default=0.0)),
                ("friendliness_score", models.FloatField(default=0.0)),
                ("combined_score", models.FloatField(default=0.0)),
                ("matched_skills", models.JSONField(default=list)),
                ("missing_skills", models.JSONField(default=list)),
                ("reasoning", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("viewed_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "contributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="skills_matching.contributorprofile",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ml_triage.issue",
                    ),
                ),
            ],
            options={
                "ordering": ["-combined_score"],
            },
        ),
        migrations.CreateModel(
            name="SkillGapAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("demand_count", models.IntegerField(default=0)),
                ("supply_count", models.IntegerField(default=0)),
                ("gap_score", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skills_matching.skilltag",
                    ),
                ),
            ],
            options={
                "ordering": ["-gap_score"],
            },
        ),
        migrations.CreateModel(
            name="IssueSkillTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confidence", models.FloatField(default=0.0)),
                ("auto_tagged", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_tags",
                        to="ml_triage.issue",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skills_matching.skilltag",
                    ),
                ),
            ],
            options={
                "unique_together": {("issue", "skill")},
            },
        ),
    ]
