# Generated by Django 5.1.15 on 2026-06-16 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_is_verified_customuser_verification_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
