# Generated by Django 5.0.14 on 2026-07-31 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.fields

class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_usersession_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="github_access_token",
            field=apps.core.fields.EncryptedCharField(
                blank=True, default="", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="github_access_token_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="google_oauth_token",
            field=apps.core.fields.EncryptedCharField(
                blank=True, default="", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="google_oauth_token_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.CreateModel(
            name="GitCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(default="github", max_length=50)),
                (
                    "token",
                    apps.core.fields.EncryptedCharField(
                        blank=True, default="", max_length=255
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "password",
                    apps.core.fields.EncryptedCharField(
                        blank=True, default="", max_length=255
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="git_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
