import hashlib
import hmac
import json
import time
from io import StringIO

import pytest
from django.conf import settings
from django.core.management import call_command
from django.test import RequestFactory, TestCase, override_settings

from apps.webhooks.middleware import WebhookSignatureMiddleware
from apps.webhooks.security import compute_signature, verify_signature


def dummy_view(request):
    from django.http import JsonResponse
    key_id = getattr(request, "webhook_key_id", None)
    return JsonResponse({"status": "ok", "key_id": key_id}, status=200)


class WebhookSignatureTestCase(TestCase):
    def setUp(self):
        self.factory = RequestFactory()
        self.secret_v1 = "secret_v1_key_value_12345"
        self.secret_v2 = "secret_v2_key_value_67890"
        self.keys = [("v1", self.secret_v1), ("v2", self.secret_v2)]
        self.middleware = WebhookSignatureMiddleware(dummy_view)
        self.payload_data = {"event": "test.completed", "user_id": 42}
        self.payload_bytes = json.dumps(self.payload_data).encode("utf-8")

    def _generate_sig(self, secret: str, body: bytes) -> str:
        return hmac.new(secret.encode("utf-8"), body, hashlib.sha256).hexdigest()

    def test_valid_signature(self):
        timestamp = str(time.time())
        signature = self._generate_sig(self.secret_v1, self.payload_bytes)

        request = self.factory.post(
            "/api/webhooks/incoming/",
            data=self.payload_bytes,
            content_type="application/json",
            HTTP_X_WEBHOOK_SIGNATURE=signature,
            HTTP_X_WEBHOOK_TIMESTAMP=timestamp,
        )

        with override_settings(WEBHOOK_SIGNING_KEYS=self.keys):
            response = self.middleware(request)

        assert response.status_code == 200
        assert getattr(request, "webhook_key_id") == "v1"

    def test_key_rotation_fallback_key_verified(self):
        """Test that a signature generated by an older key in the key ring verifies correctly."""
        timestamp = str(time.time())
        signature = self._generate_sig(self.secret_v2, self.payload_bytes)

        request = self.factory.post(
            "/api/webhooks/incoming/",
            data=self.payload_bytes,
            content_type="application/json",
            HTTP_X_WEBHOOK_SIGNATURE=signature,
            HTTP_X_WEBHOOK_TIMESTAMP=timestamp,
        )

        with override_settings(WEBHOOK_SIGNING_KEYS=self.keys):
            response = self.middleware(request)

        assert response.status_code == 200
        assert getattr(request, "webhook_key_id") == "v2"

    def test_expired_timestamp_rejected(self):
        """Test that requests with X-Webhook-Timestamp older than 5 minutes are rejected."""
        expired_timestamp = str(time.time() - 360)  # 6 minutes ago
        signature = self._generate_sig(self.secret_v1, self.payload_bytes)

        request = self.factory.post(
            "/api/webhooks/incoming/",
            data=self.payload_bytes,
            content_type="application/json",
            HTTP_X_WEBHOOK_SIGNATURE=signature,
            HTTP_X_WEBHOOK_TIMESTAMP=expired_timestamp,
        )

        with override_settings(WEBHOOK_SIGNING_KEYS=self.keys, WEBHOOK_TIMESTAMP_WINDOW_SECONDS=300):
            response = self.middleware(request)

        assert response.status_code == 400
        body = json.loads(response.content)
        assert "expired" in body["error"].lower() or "window" in body["error"].lower()

    def test_revoked_or_invalid_key_rejected(self):
        """Test that requests signed with an unknown or revoked key are rejected."""
        timestamp = str(time.time())
        revoked_sig = self._generate_sig("revoked_secret_key", self.payload_bytes)

        request = self.factory.post(
            "/api/webhooks/incoming/",
            data=self.payload_bytes,
            content_type="application/json",
            HTTP_X_WEBHOOK_SIGNATURE=revoked_sig,
            HTTP_X_WEBHOOK_TIMESTAMP=timestamp,
        )

        with override_settings(WEBHOOK_SIGNING_KEYS=self.keys):
            response = self.middleware(request)

        assert response.status_code == 403
        body = json.loads(response.content)
        assert "invalid" in body["error"].lower()

    def test_missing_signature_header_rejected(self):
        timestamp = str(time.time())
        request = self.factory.post(
            "/api/webhooks/incoming/",
            data=self.payload_bytes,
            content_type="application/json",
            HTTP_X_WEBHOOK_TIMESTAMP=timestamp,
        )

        with override_settings(WEBHOOK_SIGNING_KEYS=self.keys):
            response = self.middleware(request)

        assert response.status_code == 401
        body = json.loads(response.content)
        assert "signature" in body["error"].lower()

    def test_missing_timestamp_header_rejected(self):
        signature = self._generate_sig(self.secret_v1, self.payload_bytes)
        request = self.factory.post(
            "/api/webhooks/incoming/",
            data=self.payload_bytes,
            content_type="application/json",
            HTTP_X_WEBHOOK_SIGNATURE=signature,
        )

        with override_settings(WEBHOOK_SIGNING_KEYS=self.keys):
            response = self.middleware(request)

        assert response.status_code == 400
        body = json.loads(response.content)
        assert "timestamp" in body["error"].lower()

    def test_tampered_body_rejected(self):
        timestamp = str(time.time())
        signature = self._generate_sig(self.secret_v1, self.payload_bytes)

        tampered_bytes = json.dumps({"event": "test.completed", "user_id": 9999}).encode("utf-8")

        request = self.factory.post(
            "/api/webhooks/incoming/",
            data=tampered_bytes,
            content_type="application/json",
            HTTP_X_WEBHOOK_SIGNATURE=signature,
            HTTP_X_WEBHOOK_TIMESTAMP=timestamp,
        )

        with override_settings(WEBHOOK_SIGNING_KEYS=self.keys):
            response = self.middleware(request)

        assert response.status_code == 403

    def test_replay_attack_within_window_passes_timestamp(self):
        """Valid timestamp within 5-minute window passes timestamp validation."""
        fresh_timestamp = str(time.time() - 60)  # 1 minute ago
        signature = self._generate_sig(self.secret_v1, self.payload_bytes)

        request = self.factory.post(
            "/api/webhooks/incoming/",
            data=self.payload_bytes,
            content_type="application/json",
            HTTP_X_WEBHOOK_SIGNATURE=signature,
            HTTP_X_WEBHOOK_TIMESTAMP=fresh_timestamp,
        )

        with override_settings(WEBHOOK_SIGNING_KEYS=self.keys, WEBHOOK_TIMESTAMP_WINDOW_SECONDS=300):
            response = self.middleware(request)

        assert response.status_code == 200

    def test_rotate_webhook_signing_key_command(self):
        """Test that rotate_webhook_signing_key creates a new key and outputs deprecation notice for old active key."""
        out = StringIO()
        initial_keys = [("old_v1", "old_secret_value_123")]

        with override_settings(WEBHOOK_SIGNING_KEYS=initial_keys):
            call_command("rotate_webhook_signing_key", stdout=out)
            output = out.getvalue()

            assert "Successfully rotated webhook signing key" in output
            assert "DEPRECATION NOTICE: Key 'old_v1'" in output
            assert len(settings.WEBHOOK_SIGNING_KEYS) == 2
            assert settings.WEBHOOK_SIGNING_KEYS[1] == ("old_v1", "old_secret_value_123")
