# Generated by Django 5.0.14 on 2026-08-30 12:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("lesson", "Lesson"),
                            ("exercise", "Exercise"),
                            ("quiz", "Quiz"),
                            ("sandbox", "Sandbox"),
                            ("peer_review", "Peer Review"),
                            ("challenge", "Challenge"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "activity_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="FK id of the related Lesson/Exercise/etc.",
                        null=True,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        default=0, help_text="Elapsed seconds for the session."
                    ),
                ),
                ("xp_earned", models.IntegerField(default=0)),
                (
                    "score",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Quiz score 0-100 if applicable.",
                        null=True,
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="SkillTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon_emoji", models.CharField(default="📚", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="learning_analytics.skilltag",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SessionSkillTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=1.0, help_text="0-1 confidence of the tag assignment."
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_tags",
                        to="learning_analytics.learningsession",
                    ),
                ),
                (
                    "skill_tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_sessions",
                        to="learning_analytics.skilltag",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LearningGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("xp_target", "XP Target"),
                            ("lesson_count", "Lesson Count"),
                            ("streak_target", "Streak Target"),
                            ("skill_level", "Skill Level"),
                            ("quiz_average", "Quiz Average"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "target_value",
                    models.PositiveIntegerField(
                        help_text="Numeric target (e.g. 1000 XP, 10 lessons)."
                    ),
                ),
                ("current_value", models.PositiveIntegerField(default=0)),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("deadline", models.DateField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "skill_tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_goals",
                        to="learning_analytics.skilltag",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSkillProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(
                        default=0, help_text="Computed skill level 0-100."
                    ),
                ),
                ("total_sessions", models.PositiveIntegerField(default=0)),
                ("total_xp", models.IntegerField(default=0)),
                ("average_score", models.FloatField(default=0.0)),
                ("last_practiced", models.DateTimeField(blank=True, null=True)),
                (
                    "trend",
                    models.CharField(
                        choices=[
                            ("rising", "Rising"),
                            ("stable", "Stable"),
                            ("declining", "Declining"),
                        ],
                        default="stable",
                        max_length=10,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "skill_tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profiles",
                        to="learning_analytics.skilltag",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-level"],
            },
        ),
        migrations.CreateModel(
            name="DailyLearningMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("total_minutes", models.PositiveIntegerField(default=0)),
                ("lessons_completed", models.PositiveIntegerField(default=0)),
                ("exercises_completed", models.PositiveIntegerField(default=0)),
                ("quizzes_taken", models.PositiveIntegerField(default=0)),
                ("average_quiz_score", models.FloatField(default=0.0)),
                ("xp_earned", models.IntegerField(default=0)),
                ("streak_days", models.PositiveIntegerField(default=0)),
                ("unique_skills_practiced", models.PositiveIntegerField(default=0)),
                (
                    "focus_score",
                    models.FloatField(
                        default=0.0, help_text="0-1 ratio of focused vs idle time."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_learning_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["user", "-date"], name="idx_dlm_user_date")
                ],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="LearningInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("streak", "Streak Insight"),
                            ("skill_gap", "Skill Gap"),
                            ("momentum", "Momentum Change"),
                            ("milestone", "Milestone Near"),
                            ("warning", "Warning"),
                            ("tip", "Learning Tip"),
                            ("weekly_summary", "Weekly Summary"),
                            ("monthly_recap", "Monthly Recap"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(0, "Low"), (1, "Medium"), (2, "High")], default=1
                    ),
                ),
                (
                    "action_url",
                    models.URLField(
                        blank=True, help_text="Deep-link the user to the relevant page."
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("is_dismissed", models.BooleanField(default=False)),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extra payload for the frontend to render.",
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_insights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "-generated_at"],
                "indexes": [
                    models.Index(fields=["user", "is_read"], name="idx_li_user_read"),
                    models.Index(
                        fields=["user", "insight_type"], name="idx_li_user_type"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="learningsession",
            index=models.Index(
                fields=["user", "activity_type"], name="idx_ls_user_activity"
            ),
        ),
        migrations.AddIndex(
            model_name="learningsession",
            index=models.Index(fields=["user", "-started_at"], name="idx_ls_user_time"),
        ),
        migrations.AlterUniqueTogether(
            name="sessionskilltag",
            unique_together={("session", "skill_tag")},
        ),
        migrations.AddIndex(
            model_name="learninggoal",
            index=models.Index(
                fields=["user", "is_completed"], name="idx_lg_user_completed"
            ),
        ),
        migrations.AddIndex(
            model_name="userskillprofile",
            index=models.Index(fields=["user", "-level"], name="idx_usp_user_level"),
        ),
        migrations.AlterUniqueTogether(
            name="userskillprofile",
            unique_together={("user", "skill_tag")},
        ),
    ]
