# Generated by Django 5.0.14 on 2026-08-31 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Why this path was generated and what it covers.')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('mixed', 'Mixed')], default='mixed', max_length=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived'), ('paused', 'Paused')], db_index=True, default='active', max_length=12)),
                ('estimated_minutes', models.PositiveIntegerField(default=0, help_text='Estimated total duration in minutes.')),
                ('total_steps', models.PositiveIntegerField(default=0)),
                ('completed_steps', models.PositiveIntegerField(default=0)),
                ('xp_reward', models.IntegerField(default=0, help_text='Total XP earned from this path so far.')),
                ('priority_score', models.FloatField(default=0.0, help_text='Engine-generated priority (0-100). Higher = more relevant.')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra data: reason, strategy, engine version.')),
                ('target_skills', models.ManyToManyField(blank=True, help_text='Primary skills this path aims to develop.', related_name='targeted_learning_paths', to='learning_analytics.skilltag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority_score', '-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningPathStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(help_text='1-based position in the path.')),
                ('step_type', models.CharField(choices=[('lesson', 'Lesson'), ('exercise', 'Exercise'), ('quiz', 'Quiz'), ('challenge', 'Challenge'), ('review', 'Review'), ('milestone', 'Milestone')], default='lesson', max_length=15)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='not_started', max_length=15)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Why this step is recommended at this point.')),
                ('activity_type', models.CharField(blank=True, choices=[('lesson', 'Lesson'), ('exercise', 'Exercise'), ('quiz', 'Quiz'), ('sandbox', 'Sandbox'), ('peer_review', 'Peer Review'), ('challenge', 'Challenge')], help_text='Maps to the session activity type for tracking.', max_length=20, null=True)),
                ('activity_id', models.PositiveIntegerField(blank=True, help_text='FK id of the related content object.', null=True)),
                ('estimated_minutes', models.PositiveIntegerField(default=15, help_text='Estimated time for this step.')),
                ('xp_reward', models.IntegerField(default=10, help_text='XP awarded on step completion.')),
                ('is_milestone', models.BooleanField(default=False)),
                ('reasoning', models.TextField(blank=True, help_text='Why the engine chose this step.')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='learning_analytics.learningpath')),
                ('skill_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_path_steps', to='learning_analytics.skilltag')),
            ],
            options={
                'ordering': ['path', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='UserPathProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('active_path_count', models.PositiveIntegerField(default=0)),
                ('steps_completed_today', models.PositiveIntegerField(default=0)),
                ('xp_earned_today', models.IntegerField(default=0)),
                ('total_path_minutes_today', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_progress_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['user', 'status'], name='idx_lp_user_status'),
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['user', '-priority_score'], name='idx_lp_user_priority'),
        ),
        migrations.AddIndex(
            model_name='learningpathstep',
            index=models.Index(fields=['path', 'step_number'], name='idx_lps_path_step'),
        ),
        migrations.AddIndex(
            model_name='learningpathstep',
            index=models.Index(fields=['path', 'status'], name='idx_lps_path_status'),
        ),
        migrations.AlterUniqueTogether(
            name='learningpathstep',
            unique_together={('path', 'step_number')},
        ),
        migrations.AddIndex(
            model_name='userpathprogress',
            index=models.Index(fields=['user', '-date'], name='idx_upp_user_date'),
        ),
        migrations.AlterUniqueTogether(
            name='userpathprogress',
            unique_together={('user', 'date')},
        ),
    ]
