# Generated by Django 5.0.14 on 2026-08-19 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('model_file', models.CharField(max_length=500)),
                ('feature_names', models.JSONField(default=list)),
                ('total_samples', models.IntegerField()),
            ],
            options={
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.IntegerField(unique=True)),
                ('repository', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('title', models.TextField()),
                ('body', models.TextField(blank=True)),
                ('state', models.CharField(default='open', max_length=20)),
                ('author', models.CharField(max_length=255)),
                ('assignees', models.JSONField(default=list)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('predicted_category', models.CharField(blank=True, choices=[('bug', 'Bug'), ('feature', 'Feature Request'), ('documentation', 'Documentation'), ('question', 'Question'), ('other', 'Other')], max_length=20, null=True)),
                ('predicted_priority', models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20, null=True)),
                ('priority_score', models.FloatField(default=0.0)),
                ('hotness_score', models.FloatField(default=0.0)),
                ('lifetime_prediction_days', models.FloatField(blank=True, null=True)),
                ('feature_vector', models.JSONField(blank=True, null=True)),
                ('model_version', models.CharField(default='1.0', max_length=50)),
                ('comments_count', models.IntegerField(default=0)),
                ('reactions_count', models.IntegerField(default=0)),
                ('label_count', models.IntegerField(default=0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at_local', models.DateTimeField(auto_now_add=True)),
                ('updated_at_local', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority_score'],
                'indexes': [models.Index(fields=['repository', 'state'], name='ml_triage_i_reposit_0ff444_idx'), models.Index(fields=['priority_score'], name='ml_triage_i_priorit_2bbb3d_idx'), models.Index(fields=['predicted_category'], name='ml_triage_i_predict_9b6244_idx'), models.Index(fields=['created_at'], name='ml_triage_i_created_35b301_idx')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ml_triage.issue')),
            ],
        ),
        migrations.CreateModel(
            name='IssuePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=50)),
                ('priority', models.CharField(max_length=20)),
                ('confidence', models.FloatField()),
                ('lifetime_days', models.FloatField()),
                ('model_version', models.CharField(max_length=50)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='ml_triage.issue')),
            ],
            options={
                'ordering': ['-predicted_at'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('reaction_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='ml_triage.issue')),
            ],
        ),
    ]
