# Generated by Django 5.0.14 on 2026-08-30 12:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReflectionPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "prompt_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("challenge", "Challenge"),
                            ("milestone", "Milestone"),
                        ],
                        default="daily",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Optional category tag for the prompt.",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("times_used", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-times_used"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True,
                        help_text="The calendar date this entry reflects on.",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional title for the entry.",
                        max_length=255,
                    ),
                ),
                (
                    "what_i_learned",
                    models.TextField(help_text="What did you learn today?"),
                ),
                (
                    "challenges_faced",
                    models.TextField(
                        blank=True, help_text="What was difficult or confusing?"
                    ),
                ),
                (
                    "key_takeaways",
                    models.TextField(
                        blank=True, help_text="Key insights or takeaways."
                    ),
                ),
                (
                    "tomorrow_goals",
                    models.TextField(
                        blank=True,
                        help_text="What do you want to learn or accomplish tomorrow?",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Free-form tags, e.g. ["python", "debugging"].',
                    ),
                ),
                (
                    "mood",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "😫 Terrible"),
                            (2, "😕 Bad"),
                            (3, "😐 Okay"),
                            (4, "😊 Good"),
                            (5, "🤩 Great"),
                        ],
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "productivity_score",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="Self-rated productivity 1-10.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "hours_spent",
                    models.FloatField(
                        default=0.0, help_text="Approximate hours spent learning."
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("mentors", "Mentors Only"),
                            ("public", "Public"),
                        ],
                        default="private",
                        max_length=10,
                    ),
                ),
                (
                    "linked_lessons",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Lesson slugs linked to this entry, e.g. ["git-basics"].',
                    ),
                ),
                ("linked_flashcard_decks", models.JSONField(blank=True, default=list)),
                ("xp_earned", models.PositiveIntegerField(default=0)),
                ("word_count", models.PositiveIntegerField(default=0)),
                ("is_bookmarked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JournalComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "is_mentor_note",
                    models.BooleanField(
                        default=False, help_text="Comment from a mentor with feedback."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="learning_journal.journalentry",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="JournalReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[
                            ("like", "👍 Like"),
                            ("encourage", "💪 Encourage"),
                            ("insightful", "💡 Insightful"),
                            ("celebrate", "🎉 Celebrate"),
                        ],
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="learning_journal.journalentry",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JournalTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "sections",
                    models.JSONField(
                        default=list,
                        help_text='List of section titles, e.g. ["What I learned", "Challenges", "Goals"].',
                    ),
                ),
                ("default_tags", models.JSONField(blank=True, default=list)),
                ("clone_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-clone_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserReflectionStreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_streak", models.PositiveIntegerField(default=0)),
                ("longest_streak", models.PositiveIntegerField(default=0)),
                ("last_entry_date", models.DateField(blank=True, null=True)),
                ("total_entries", models.PositiveIntegerField(default=0)),
                ("total_words_written", models.PositiveIntegerField(default=0)),
                ("total_hours_reflected", models.FloatField(default=0.0)),
                ("average_mood", models.FloatField(default=0.0)),
                ("average_productivity", models.FloatField(default=0.0)),
                (
                    "favorite_day",
                    models.CharField(
                        blank=True,
                        help_text="Day of week with most entries.",
                        max_length=10,
                    ),
                ),
                (
                    "favorite_tag",
                    models.CharField(
                        blank=True, help_text="Most frequently used tag.", max_length=50
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_streak",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User reflection streaks",
            },
        ),
        migrations.CreateModel(
            name="WeeklyReflection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start", models.DateField(help_text="Monday of the ISO week.")),
                (
                    "summary",
                    models.TextField(
                        help_text="Auto-generated summary of the week's entries."
                    ),
                ),
                ("entries_count", models.PositiveIntegerField(default=0)),
                ("total_words", models.PositiveIntegerField(default=0)),
                ("total_hours", models.FloatField(default=0.0)),
                ("average_mood", models.FloatField(default=0.0)),
                ("average_productivity", models.FloatField(default=0.0)),
                (
                    "mood_trend",
                    models.CharField(
                        choices=[
                            ("improving", "Improving"),
                            ("stable", "Stable"),
                            ("declining", "Declining"),
                        ],
                        default="stable",
                        max_length=10,
                    ),
                ),
                ("top_tags", models.JSONField(default=list)),
                (
                    "highlights",
                    models.JSONField(
                        default=list,
                        help_text="Key highlights from the week's entries.",
                    ),
                ),
                ("goals_for_next_week", models.TextField(blank=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_reflections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-week_start"],
            },
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(fields=["user", "-date"], name="idx_je_user_date"),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(fields=["user", "mood"], name="idx_je_user_mood"),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(fields=["visibility", "-date"], name="idx_je_vis_date"),
        ),
        migrations.AlterUniqueTogether(
            name="journalentry",
            unique_together={("user", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="journalreaction",
            unique_together={("entry", "user", "reaction_type")},
        ),
        migrations.AlterUniqueTogether(
            name="weeklyreflection",
            unique_together={("user", "week_start")},
        ),
    ]
