# Generated by Django 5.0.14 on 2026-08-30 12:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MentorshipMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skill_focus",
                    models.SlugField(
                        blank=True,
                        help_text="Primary skill this mentorship focuses on.",
                    ),
                ),
                (
                    "goals",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Structured learning goals for this mentorship.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("terminated", "Terminated"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("total_sessions", models.PositiveIntegerField(default=0)),
                ("total_hours", models.FloatField(default=0.0)),
                ("mentor_xp_earned", models.PositiveIntegerField(default=0)),
                ("mentee_xp_earned", models.PositiveIntegerField(default=0)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Shared notes between mentor and mentee."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mentee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentorship_matches_as_mentee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentorship_matches_as_mentor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MentorshipGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("achieved", "Achieved"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("target_date", models.DateField(blank=True, null=True)),
                ("achieved_date", models.DateField(blank=True, null=True)),
                (
                    "progress_pct",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_mentorship_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentorship_goals",
                        to="mentorship.mentorshipmatch",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MentorshipFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("mentor_on_mentee", "Mentor → Mentee"),
                            ("mentee_on_mentor", "Mentee → Mentor"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "overall_rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "communication_rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "helpfulness_rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "is_anonymous",
                    models.BooleanField(
                        default=False,
                        help_text="Hide the reviewer's identity from the report.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_mentorship_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_mentorship_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="mentorship.mentorshipmatch",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MentorshipMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("xp_awarded", models.PositiveIntegerField(default=50)),
                ("achieved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="mentorship.mentorshipmatch",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentorship_milestones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-achieved_at"],
            },
        ),
        migrations.CreateModel(
            name="MentorshipRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="What you want to learn.", max_length=255
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Introduction and learning goals."
                    ),
                ),
                (
                    "skill_wanted",
                    models.SlugField(
                        blank=True,
                        help_text="Specific skill slug the mentee wants help with.",
                    ),
                ),
                (
                    "preferred_frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("biweekly", "Bi-Weekly"),
                            ("monthly", "Monthly"),
                            ("flexible", "Flexible"),
                        ],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "response_message",
                    models.TextField(
                        blank=True, help_text="Mentor's response message."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Request auto-expires after this time."
                    ),
                ),
                (
                    "mentee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentorship_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="mentorshipmatch",
            name="request",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="match",
                to="mentorship.mentorshiprequest",
            ),
        ),
        migrations.CreateModel(
            name="MentorshipSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=15,
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=30, help_text="Actual or planned session duration."
                    ),
                ),
                (
                    "topics_covered",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Topics discussed, e.g. ["git merge", "rebasing"].',
                    ),
                ),
                (
                    "action_items",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Follow-up tasks for the mentee.",
                    ),
                ),
                (
                    "mentee_notes",
                    models.TextField(
                        blank=True, help_text="Notes from the mentee's perspective."
                    ),
                ),
                (
                    "mentor_notes",
                    models.TextField(
                        blank=True, help_text="Notes from the mentor's perspective."
                    ),
                ),
                (
                    "mentor_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Mentee's rating of the mentor for this session.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "mentee_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Mentor's rating of the mentee for this session.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("mentor_feedback", models.TextField(blank=True)),
                ("mentee_feedback", models.TextField(blank=True)),
                ("xp_awarded_mentor", models.PositiveIntegerField(default=0)),
                ("xp_awarded_mentee", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="mentorship.mentorshipmatch",
                    ),
                ),
                (
                    "mentee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentoring_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentored_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="MentorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Short bio describing mentoring style and expertise.",
                    ),
                ),
                (
                    "expertise_areas",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of skill slugs, e.g. ["python", "git-basics"].',
                    ),
                ),
                (
                    "years_experience",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Approximate years of programming experience.",
                    ),
                ),
                (
                    "max_mentees",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Maximum concurrent mentees.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                ("current_mentee_count", models.PositiveIntegerField(default=0)),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("busy", "Busy"),
                            ("unavailable", "Unavailable"),
                        ],
                        db_index=True,
                        default="available",
                        max_length=15,
                    ),
                ),
                (
                    "preferred_session_duration",
                    models.PositiveIntegerField(
                        default=30, help_text="Preferred session length in minutes."
                    ),
                ),
                (
                    "languages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Spoken languages, e.g. ["en", "es"].',
                    ),
                ),
                (
                    "timezone_name",
                    models.CharField(blank=True, default="UTC", max_length=50),
                ),
                ("total_sessions_mentored", models.PositiveIntegerField(default=0)),
                ("total_hours_mentored", models.FloatField(default=0.0)),
                (
                    "average_rating",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                ("rating_count", models.PositiveIntegerField(default=0)),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Verified by an admin after review."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentorship_mentor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-average_rating", "-total_sessions_mentored"],
                "indexes": [
                    models.Index(
                        fields=["availability", "-average_rating"],
                        name="idx_mp_avail_rating",
                    ),
                    models.Index(
                        fields=["is_active", "availability"], name="idx_mp_active_avail"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="mentorshiprequest",
            index=models.Index(
                fields=["mentor", "status"], name="idx_mr_mentor_status"
            ),
        ),
        migrations.AddIndex(
            model_name="mentorshiprequest",
            index=models.Index(
                fields=["mentee", "status"], name="idx_mr_mentee_status"
            ),
        ),
        migrations.AddIndex(
            model_name="mentorshipmatch",
            index=models.Index(
                fields=["mentor", "status"], name="idx_mm_mentor_status"
            ),
        ),
        migrations.AddIndex(
            model_name="mentorshipmatch",
            index=models.Index(
                fields=["mentee", "status"], name="idx_mm_mentee_status"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mentorshipmatch",
            unique_together={("mentor", "mentee")},
        ),
        migrations.AddIndex(
            model_name="mentorshipsession",
            index=models.Index(fields=["match", "status"], name="idx_ms_match_status"),
        ),
        migrations.AddIndex(
            model_name="mentorshipsession",
            index=models.Index(
                fields=["scheduled_at", "status"], name="idx_ms_sched_status"
            ),
        ),
    ]
